### PR TITLE
Support for PG11 in the tests

### PR DESCRIPTION
**Pull request by ethervoid**

### CODE REVIEW

**Comment by dgaubert** [comment]
I'm afraid PG11 isn't supported yet by Travis. 😭

**Comment by ethervoid** [comment]
@dgaubert Yep it is, is installing it but I'm not going to follow that path. I'm going to use our own docker images with our PPA packages to tests against our own dog food :D

**Comment by dgaubert** [comment]
_Aprovechando que el Pisuerga pasa por Valladolid_. Please, drop support for Node.js < 10 and bump a major version.

**Comment by Algunenano** [comment]
It's dangerous to go alone. [Take this](https://github.com/CartoDB/cartodb-postgresql/blob/master/.travis.yml)

**Comment by ethervoid** [comment]
@dgaubert yep, I was going to leave only node 10

@Algunenano I'd change that to use our own docker images with our PPA packages which is more realistic for us :)

**Comment by ethervoid** [comment]
@Algunenano @dgaubert done!

**Review by Algunenano — APPROVED** [review]
LGTM

**Pull request merged**
