### PR TITLE
accept parameters

### PR DESCRIPTION
**Pull request by calvinmetcalf**
allow parameterized queries

### CODE REVIEW

**Comment by rochoa** [comment]
Hi @calvinmetcalf 

Nice to have this kind of contributions! It would be really nice if you can introduce some basic tests using `params`. Do you feel OK adding some? :-)

btw if you upgrade with latest master it will stop testing node 0.8.x so you will get travis not complaining about it.

**Comment by calvinmetcalf** [comment]
will add a test, I have something screwy on my system preventing me from using node-gyp with node (as opposed to iojs)

**Comment by calvinmetcalf** [comment]
take that back, gives errors but builds fine, will add some tests

**Comment by calvinmetcalf** [comment]
tests added

**Comment by calvinmetcalf** [comment]
all right, noticed that the tests where not actually running in travis so fixed that and switched it over to the [container based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/) so it would go faster

**Comment by rochoa** [comment]
Thanks a lot for the contribution @calvinmetcalf! :+1:

**Pull request merged**
